### ISSUE TITLE
DIO BNC v1.2 errata

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/DIO_BNC#1]
_From @gkasprow on [2018-03-08 12:24](https://github.com/sinara-hw/sinara/issues/527)_

- [x] make panel holes for BNC connectors smaller - the screw size is 10.3mm but hole is 13mm. 
The same applies to Sampler panel.
- [x] swap channels 4/5 and 6/7 (J3 with J4)
- [x] fix LED order - in channels: 2/3 4/5 6/7 top LEDs are swapped with bottom ones

**Comment by gkasprow** [comment]
Datasheet says that the PCB hole should be 12.15mm.
