### ISSUE TITLE
input protection

### ISSUE THREAD

**Issue by jordens** [sinara-hw/DIO_BNC#12]
Currently, input channels are limited by the -0.5 to 5.5 V abs max of the buffer. The body diode of the termination mosfet helps a bit with negative voltages below that. And there is also ESD protection.
We've seen latchup. Is there an easy way to protect the channels against a larger input voltage range? The bidirectional design is a bit of a hindrance here and the unused outputs look like they are most at risk.

* Applies also to DIO-SMA
* Also ties into the in-out partitioning and configurability of #11

**Comment by gkasprow** [comment]
What about such circuit? 
![obraz](https://user-images.githubusercontent.com/4325054/86416447-35c8f700-bcca-11ea-9b62-6a70ebdec0d8.png)
