### ISSUE TITLE
Wiki: Input Signal Range

### ISSUE THREAD

**Issue by pathfinder49** [sinara-hw/DIO_BNC#14]
It'd be nice to add the working input voltage range to the wiki. From the SN74BCT25245DW datasheet, it looks like the working range is -0.5 to 5.5 V. (Though the upper limit drops to 5 V when the connection is set as output.)

The wiki also states:
> Max 150 MHz toggle rate with 50% duty cycle

I assume this applies to both input and output signals?

**Comment by gkasprow** [comment]
Done
150MHz applies to both I and O.
