### ISSUE TITLE
v1.6 resistors changes

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/DIO_BNC#16]
Due to wrong resistive divider, enable of isolators and transceiver direction couldn't be changed. Resistors values are changed to:

<html>
<body>

Des. | Value
-- | --
R45 | 3k9
R44 | 1k
R48 | 510
R56 | 470
R57 | 470
R50 | 3k9
R49 | 1k
R53 | 510
R58 | 470
R59 | 470

</body>
</html>

**Comment by gkasprow** [comment]
The LEDs must be connected to a dedicated MOSFET in the next revision to keep uniform brightness.

**Comment by filipswit** [comment]
Yes, I was thinking about either MOSFET or buffer (kind of this: SN74AHCT1G125DBVT) after transoptor.

**Comment by gkasprow** [comment]
let's not add things to the BOM. MOSFET is fine.
