### ISSUE TITLE
labelling

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/DIO_BNC#8]
R18 and R25 are quite important. Worth silk screen to identify them, as well as an annotation ("High-impedance connection between grounds to prevent build-up of charge" or something like that).

Same goes for R34/R35 C6 and C5. Annotation would be something like ("Connects panel to circuit ground, remove to float grounds").

Without these annotations, it's obvious what these are for.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/86417442-4fb80900-bccd-11ea-9128-f009b7d19cff.png)
