### ISSUE TITLE
remove DNP SMPSs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/DIO_BNC#9]
Given that the Murata SMPS works nicely, while we had repeated failures with the other one, I suggest we completely remove the DNPd one from the schematic/layout in the next revision to clean things up a little.

**Comment by gkasprow** [comment]
I'm afraid that Murata does not produce these converters anymore :(

**Comment by gkasprow** [comment]
we need to use TMH1205S. We can keep the Murata footprint just in case somebody has a stock of these components

**Comment by gkasprow** [comment]
we can also go for RKZ-1205S

**Comment by gkasprow** [comment]
That's strange. I was sure I saw this product as not produced anymore.
But now it is active...

**Comment by gkasprow** [comment]
They have a lead time somewhere in December 2020..
